export interface CityZone {
  id: string
  name: string
  country: string
  zone: string
}

export const ALL_CITIES: CityZone[] = [
  // --- ITALY (Deep Regional Coverage) ---
  { id: 'rom', name: 'Rome', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'mil', name: 'Milan', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'nap', name: 'Naples', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'trn', name: 'Turin (Torino)', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'pmo', name: 'Palermo', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'goa', name: 'Genoa (Genova)', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'blq', name: 'Bologna', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'flr', name: 'Florence (Firenze)', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'cta', name: 'Catania', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'bri', name: 'Bari', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'vce', name: 'Venice (Venezia)', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'vrn', name: 'Verona', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'msn', name: 'Messina', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'pad', name: 'Padua (Padova)', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'trs', name: 'Trieste', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'vbs', name: 'Brescia', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'pmf', name: 'Parma', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'tar', name: 'Taranto', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'mod', name: 'Modena', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'rca', name: 'Reggio Calabria', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'rem', name: 'Reggio Emilia', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'peg', name: 'Perugia', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'rav', name: 'Ravenna', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'liv', name: 'Livorno', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'cag', name: 'Cagliari', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'fgg', name: 'Foggia', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'rni', name: 'Rimini', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'sal', name: 'Salerno', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'fer', name: 'Ferrara', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'psa', name: 'Pisa', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'sie', name: 'Siena', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'bgy', name: 'Bergamo', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'syr_it', name: 'Syracuse (Siracusa)', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'tnt', name: 'Trento', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'bzo', name: 'Bolzano (Bozen)', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'aoi', name: 'Ancona', country: 'Italy', zone: 'Europe/Rome' },

  // --- CYPRUS & GREECE ---
  { id: 'nic', name: 'Nicosia', country: 'Cyprus', zone: 'Asia/Nicosia' },
  { id: 'lim', name: 'Limassol', country: 'Cyprus', zone: 'Asia/Nicosia' },
  { id: 'lca', name: 'Larnaca', country: 'Cyprus', zone: 'Asia/Nicosia' },
  { id: 'pfo', name: 'Paphos', country: 'Cyprus', zone: 'Asia/Nicosia' },
  { id: 'ayn', name: 'Ayia Napa', country: 'Cyprus', zone: 'Asia/Nicosia' },
  { id: 'ath', name: 'Athens', country: 'Greece', zone: 'Europe/Athens' },
  { id: 'skg', name: 'Thessaloniki', country: 'Greece', zone: 'Europe/Athens' },
  { id: 'gpa', name: 'Patras', country: 'Greece', zone: 'Europe/Athens' },
  { id: 'her', name: 'Heraklion', country: 'Greece', zone: 'Europe/Athens' },
  { id: 'lar', name: 'Larissa', country: 'Greece', zone: 'Europe/Athens' },
  { id: 'vol', name: 'Volos', country: 'Greece', zone: 'Europe/Athens' },
  { id: 'ioa', name: 'Ioannina', country: 'Greece', zone: 'Europe/Athens' },
  { id: 'chq', name: 'Chania', country: 'Greece', zone: 'Europe/Athens' },
  { id: 'rho', name: 'Rhodes', country: 'Greece', zone: 'Europe/Athens' },
  { id: 'cfu', name: 'Corfu (Kerkyra)', country: 'Greece', zone: 'Europe/Athens' },

  // --- WESTERN & CENTRAL EUROPE ---
  { id: 'lon', name: 'London', country: 'United Kingdom', zone: 'Europe/London' },
  { id: 'bhx', name: 'Birmingham', country: 'United Kingdom', zone: 'Europe/London' },
  { id: 'man', name: 'Manchester', country: 'United Kingdom', zone: 'Europe/London' },
  { id: 'gla', name: 'Glasgow', country: 'United Kingdom', zone: 'Europe/London' },
  { id: 'liv_uk', name: 'Liverpool', country: 'United Kingdom', zone: 'Europe/London' },
  { id: 'brs', name: 'Bristol', country: 'United Kingdom', zone: 'Europe/London' },
  { id: 'edi', name: 'Edinburgh', country: 'United Kingdom', zone: 'Europe/London' },
  { id: 'lds', name: 'Leeds', country: 'United Kingdom', zone: 'Europe/London' },
  { id: 'shf', name: 'Sheffield', country: 'United Kingdom', zone: 'Europe/London' },
  { id: 'ncl', name: 'Newcastle', country: 'United Kingdom', zone: 'Europe/London' },
  { id: 'bfs', name: 'Belfast', country: 'United Kingdom', zone: 'Europe/London' },
  { id: 'cwl', name: 'Cardiff', country: 'United Kingdom', zone: 'Europe/London' },
  { id: 'oxf', name: 'Oxford', country: 'United Kingdom', zone: 'Europe/London' },
  { id: 'cbx', name: 'Cambridge', country: 'United Kingdom', zone: 'Europe/London' },
  { id: 'dub', name: 'Dublin', country: 'Ireland', zone: 'Europe/Dublin' },
  { id: 'ork', name: 'Cork', country: 'Ireland', zone: 'Europe/Dublin' },
  { id: 'par', name: 'Paris', country: 'France', zone: 'Europe/Paris' },
  { id: 'mrs', name: 'Marseille', country: 'France', zone: 'Europe/Paris' },
  { id: 'lyo', name: 'Lyon', country: 'France', zone: 'Europe/Paris' },
  { id: 'tls', name: 'Toulouse', country: 'France', zone: 'Europe/Paris' },
  { id: 'nce', name: 'Nice', country: 'France', zone: 'Europe/Paris' },
  { id: 'nte', name: 'Nantes', country: 'France', zone: 'Europe/Paris' },
  { id: 'sxb', name: 'Strasbourg', country: 'France', zone: 'Europe/Paris' },
  { id: 'mpl', name: 'Montpellier', country: 'France', zone: 'Europe/Paris' },
  { id: 'bod', name: 'Bordeaux', country: 'France', zone: 'Europe/Paris' },
  { id: 'lil', name: 'Lille', country: 'France', zone: 'Europe/Paris' },
  { id: 'ceh', name: 'Cannes', country: 'France', zone: 'Europe/Paris' },
  { id: 'ber', name: 'Berlin', country: 'Germany', zone: 'Europe/Berlin' },
  { id: 'ham', name: 'Hamburg', country: 'Germany', zone: 'Europe/Berlin' },
  { id: 'mun', name: 'Munich', country: 'Germany', zone: 'Europe/Berlin' },
  { id: 'cgn', name: 'Cologne (Köln)', country: 'Germany', zone: 'Europe/Berlin' },
  { id: 'fra', name: 'Frankfurt', country: 'Germany', zone: 'Europe/Berlin' },
  { id: 'str', name: 'Stuttgart', country: 'Germany', zone: 'Europe/Berlin' },
  { id: 'dus', name: 'Düsseldorf', country: 'Germany', zone: 'Europe/Berlin' },
  { id: 'lej', name: 'Leipzig', country: 'Germany', zone: 'Europe/Berlin' },
  { id: 'dtm', name: 'Dortmund', country: 'Germany', zone: 'Europe/Berlin' },
  { id: 'drs', name: 'Dresden', country: 'Germany', zone: 'Europe/Berlin' },
  { id: 'nue', name: 'Nuremberg (Nürnberg)', country: 'Germany', zone: 'Europe/Berlin' },
  { id: 'mad', name: 'Madrid', country: 'Spain', zone: 'Europe/Madrid' },
  { id: 'bcn', name: 'Barcelona', country: 'Spain', zone: 'Europe/Madrid' },
  { id: 'vlc', name: 'Valencia', country: 'Spain', zone: 'Europe/Madrid' },
  { id: 'svq', name: 'Seville (Sevilla)', country: 'Spain', zone: 'Europe/Madrid' },
  { id: 'zaz', name: 'Zaragoza', country: 'Spain', zone: 'Europe/Madrid' },
  { id: 'agp', name: 'Málaga', country: 'Spain', zone: 'Europe/Madrid' },
  { id: 'pmr', name: 'Palma de Mallorca', country: 'Spain', zone: 'Europe/Madrid' },
  { id: 'lpa', name: 'Las Palmas (Canary Is.)', country: 'Spain', zone: 'Atlantic/Canary' },
  { id: 'bio', name: 'Bilbao', country: 'Spain', zone: 'Europe/Madrid' },
  { id: 'alc', name: 'Alicante', country: 'Spain', zone: 'Europe/Madrid' },
  { id: 'grx', name: 'Granada', country: 'Spain', zone: 'Europe/Madrid' },
  { id: 'ibz', name: 'Ibiza', country: 'Spain', zone: 'Europe/Madrid' },
  { id: 'ams', name: 'Amsterdam', country: 'Netherlands', zone: 'Europe/Amsterdam' },
  { id: 'rtm', name: 'Rotterdam', country: 'Netherlands', zone: 'Europe/Amsterdam' },
  { id: 'hag', name: 'The Hague (Den Haag)', country: 'Netherlands', zone: 'Europe/Amsterdam' },
  { id: 'utr', name: 'Utrecht', country: 'Netherlands', zone: 'Europe/Amsterdam' },
  { id: 'ein', name: 'Eindhoven', country: 'Netherlands', zone: 'Europe/Amsterdam' },
  { id: 'bru', name: 'Brussels', country: 'Belgium', zone: 'Europe/Brussels' },
  { id: 'anr', name: 'Antwerp', country: 'Belgium', zone: 'Europe/Brussels' },
  { id: 'gnt', name: 'Ghent', country: 'Belgium', zone: 'Europe/Brussels' },
  { id: 'bge', name: 'Bruges', country: 'Belgium', zone: 'Europe/Brussels' },
  { id: 'lis', name: 'Lisbon', country: 'Portugal', zone: 'Europe/Lisbon' },
  { id: 'opo', name: 'Porto', country: 'Portugal', zone: 'Europe/Lisbon' },
  { id: 'fnc', name: 'Funchal (Madeira)', country: 'Portugal', zone: 'Atlantic/Madeira' },
  { id: 'fao', name: 'Faro (Algarve)', country: 'Portugal', zone: 'Europe/Lisbon' },
  { id: 'vie', name: 'Vienna', country: 'Austria', zone: 'Europe/Vienna' },
  { id: 'grz', name: 'Graz', country: 'Austria', zone: 'Europe/Vienna' },
  { id: 'szg', name: 'Salzburg', country: 'Austria', zone: 'Europe/Vienna' },
  { id: 'inn', name: 'Innsbruck', country: 'Austria', zone: 'Europe/Vienna' },
  { id: 'zur', name: 'Zurich', country: 'Switzerland', zone: 'Europe/Zurich' },
  { id: 'gva', name: 'Geneva', country: 'Switzerland', zone: 'Europe/Zurich' },
  { id: 'bsl', name: 'Basel', country: 'Switzerland', zone: 'Europe/Zurich' },
  { id: 'brn', name: 'Bern', country: 'Switzerland', zone: 'Europe/Zurich' },
  { id: 'lzn', name: 'Lausanne', country: 'Switzerland', zone: 'Europe/Zurich' },
  { id: 'luc', name: 'Lucerne', country: 'Switzerland', zone: 'Europe/Zurich' },
  { id: 'lug', name: 'Lugano', country: 'Switzerland', zone: 'Europe/Zurich' },

  // --- NORDICS & EASTERN EUROPE ---
  { id: 'sto', name: 'Stockholm', country: 'Sweden', zone: 'Europe/Stockholm' },
  { id: 'got', name: 'Gothenburg', country: 'Sweden', zone: 'Europe/Stockholm' },
  { id: 'osl', name: 'Oslo', country: 'Norway', zone: 'Europe/Oslo' },
  { id: 'bgo', name: 'Bergen', country: 'Norway', zone: 'Europe/Oslo' },
  { id: 'cph', name: 'Copenhagen', country: 'Denmark', zone: 'Europe/Copenhagen' },
  { id: 'aar', name: 'Aarhus', country: 'Denmark', zone: 'Europe/Copenhagen' },
  { id: 'hel', name: 'Helsinki', country: 'Finland', zone: 'Europe/Helsinki' },
  { id: 'kef', name: 'Reykjavik', country: 'Iceland', zone: 'Atlantic/Reykjavik' },
  { id: 'war', name: 'Warsaw', country: 'Poland', zone: 'Europe/Warsaw' },
  { id: 'krk', name: 'Kraków', country: 'Poland', zone: 'Europe/Warsaw' },
  { id: 'wro', name: 'Wrocław', country: 'Poland', zone: 'Europe/Warsaw' },
  { id: 'gdn', name: 'Gdańsk', country: 'Poland', zone: 'Europe/Warsaw' },
  { id: 'prg', name: 'Prague', country: 'Czech Republic', zone: 'Europe/Prague' },
  { id: 'brq', name: 'Brno', country: 'Czech Republic', zone: 'Europe/Prague' },
  { id: 'bud', name: 'Budapest', country: 'Hungary', zone: 'Europe/Budapest' },
  { id: 'buc', name: 'Bucharest', country: 'Romania', zone: 'Europe/Bucharest' },
  { id: 'clj', name: 'Cluj-Napoca', country: 'Romania', zone: 'Europe/Bucharest' },
  { id: 'tsr', name: 'Timișoara', country: 'Romania', zone: 'Europe/Bucharest' },
  { id: 'sof', name: 'Sofia', country: 'Bulgaria', zone: 'Europe/Sofia' },
  { id: 'zag', name: 'Zagreb', country: 'Croatia', zone: 'Europe/Zagreb' },
  { id: 'spu', name: 'Split', country: 'Croatia', zone: 'Europe/Zagreb' },
  { id: 'dbv', name: 'Dubrovnik', country: 'Croatia', zone: 'Europe/Zagreb' },
  { id: 'bel', name: 'Belgrade', country: 'Serbia', zone: 'Europe/Belgrade' },
  { id: 'bts', name: 'Bratislava', country: 'Slovakia', zone: 'Europe/Bratislava' },
  { id: 'lju', name: 'Ljubljana', country: 'Slovenia', zone: 'Europe/Ljubljana' },
  { id: 'kyi', name: 'Kyiv', country: 'Ukraine', zone: 'Europe/Kyiv' },
  { id: 'lwo', name: 'Lviv', country: 'Ukraine', zone: 'Europe/Kyiv' },
  { id: 'tll', name: 'Tallinn', country: 'Estonia', zone: 'Europe/Tallinn' },
  { id: 'rix', name: 'Riga', country: 'Latvia', zone: 'Europe/Riga' },
  { id: 'vno', name: 'Vilnius', country: 'Lithuania', zone: 'Europe/Vilnius' },
  { id: 'ist', name: 'Istanbul', country: 'Turkey', zone: 'Europe/Istanbul' },
  { id: 'ank', name: 'Ankara', country: 'Turkey', zone: 'Europe/Istanbul' },
  { id: 'adb', name: 'Izmir', country: 'Turkey', zone: 'Europe/Istanbul' },
  { id: 'ayt', name: 'Antalya', country: 'Turkey', zone: 'Europe/Istanbul' },

  // --- NORTH AMERICA ---
  { id: 'nyc', name: 'New York', country: 'United States', zone: 'America/New_York' },
  { id: 'bos', name: 'Boston', country: 'United States', zone: 'America/New_York' },
  { id: 'mia', name: 'Miami', country: 'United States', zone: 'America/New_York' },
  { id: 'orl', name: 'Orlando', country: 'United States', zone: 'America/New_York' },
  { id: 'atl', name: 'Atlanta', country: 'United States', zone: 'America/New_York' },
  { id: 'was', name: 'Washington D.C.', country: 'United States', zone: 'America/New_York' },
  { id: 'phl', name: 'Philadelphia', country: 'United States', zone: 'America/New_York' },
  { id: 'chi', name: 'Chicago', country: 'United States', zone: 'America/Chicago' },
  { id: 'dal', name: 'Dallas', country: 'United States', zone: 'America/Chicago' },
  { id: 'hou', name: 'Houston', country: 'United States', zone: 'America/Chicago' },
  { id: 'aus', name: 'Austin', country: 'United States', zone: 'America/Chicago' },
  { id: 'mci', name: 'Kansas City', country: 'United States', zone: 'America/Chicago' },
  { id: 'msp', name: 'Minneapolis', country: 'United States', zone: 'America/Chicago' },
  { id: 'den', name: 'Denver', country: 'United States', zone: 'America/Denver' },
  { id: 'slc', name: 'Salt Lake City', country: 'United States', zone: 'America/Denver' },
  { id: 'phx', name: 'Phoenix', country: 'United States', zone: 'America/Phoenix' },
  { id: 'lax', name: 'Los Angeles', country: 'United States', zone: 'America/Los_Angeles' },
  { id: 'san', name: 'San Diego', country: 'United States', zone: 'America/Los_Angeles' },
  { id: 'sfo', name: 'San Francisco', country: 'United States', zone: 'America/Los_Angeles' },
  { id: 'sjc', name: 'San Jose', country: 'United States', zone: 'America/Los_Angeles' },
  { id: 'sea', name: 'Seattle', country: 'United States', zone: 'America/Los_Angeles' },
  { id: 'pdx', name: 'Portland', country: 'United States', zone: 'America/Los_Angeles' },
  { id: 'las', name: 'Las Vegas', country: 'United States', zone: 'America/Los_Angeles' },
  { id: 'anc', name: 'Anchorage', country: 'United States', zone: 'America/Anchorage' },
  { id: 'hnl', name: 'Honolulu', country: 'United States', zone: 'Pacific/Honolulu' },
  { id: 'tor', name: 'Toronto', country: 'Canada', zone: 'America/Toronto' },
  { id: 'mtl', name: 'Montreal', country: 'Canada', zone: 'America/Toronto' },
  { id: 'ott', name: 'Ottawa', country: 'Canada', zone: 'America/Toronto' },
  { id: 'van', name: 'Vancouver', country: 'Canada', zone: 'America/Vancouver' },
  { id: 'cgy', name: 'Calgary', country: 'Canada', zone: 'America/Edmonton' },
  { id: 'edm', name: 'Edmonton', country: 'Canada', zone: 'America/Edmonton' },
  { id: 'mex', name: 'Mexico City', country: 'Mexico', zone: 'America/Mexico_City' },
  { id: 'gdl', name: 'Guadalajara', country: 'Mexico', zone: 'America/Mexico_City' },
  { id: 'mty', name: 'Monterrey', country: 'Mexico', zone: 'America/Monterrey' },
  { id: 'cun', name: 'Cancún', country: 'Mexico', zone: 'America/Cancun' },

  // --- LATIN AMERICA ---
  { id: 'sao', name: 'São Paulo', country: 'Brazil', zone: 'America/Sao_Paulo' },
  { id: 'rio', name: 'Rio de Janeiro', country: 'Brazil', zone: 'America/Sao_Paulo' },
  { id: 'bsb', name: 'Brasília', country: 'Brazil', zone: 'America/Sao_Paulo' },
  { id: 'bue', name: 'Buenos Aires', country: 'Argentina', zone: 'America/Argentina/Buenos_Aires' },
  { id: 'cor', name: 'Córdoba', country: 'Argentina', zone: 'America/Argentina/Cordoba' },
  { id: 'bog', name: 'Bogotá', country: 'Colombia', zone: 'America/Bogota' },
  { id: 'mde', name: 'Medellín', country: 'Colombia', zone: 'America/Bogota' },
  { id: 'lim_pe', name: 'Lima', country: 'Peru', zone: 'America/Lima' },
  { id: 'scl', name: 'Santiago', country: 'Chile', zone: 'America/Santiago' },
  { id: 'uio', name: 'Quito', country: 'Ecuador', zone: 'America/Guayaquil' },
  { id: 'gye', name: 'Guayaquil', country: 'Ecuador', zone: 'America/Guayaquil' },
  { id: 'ccs', name: 'Caracas', country: 'Venezuela', zone: 'America/Caracas' },
  { id: 'mvd', name: 'Montevideo', country: 'Uruguay', zone: 'America/Montevideo' },
  { id: 'pty', name: 'Panama City', country: 'Panama', zone: 'America/Panama' },
  { id: 'sjo', name: 'San José', country: 'Costa Rica', zone: 'America/Costa_Rica' },

  // --- MIDDLE EAST & AFRICA ---
  { id: 'dxb', name: 'Dubai', country: 'United Arab Emirates', zone: 'Asia/Dubai' },
  { id: 'auh', name: 'Abu Dhabi', country: 'United Arab Emirates', zone: 'Asia/Dubai' },
  { id: 'shj', name: 'Sharjah', country: 'United Arab Emirates', zone: 'Asia/Dubai' },
  { id: 'ruh', name: 'Riyadh', country: 'Saudi Arabia', zone: 'Asia/Riyadh' },
  { id: 'jed', name: 'Jeddah', country: 'Saudi Arabia', zone: 'Asia/Riyadh' },
  { id: 'doh', name: 'Doha', country: 'Qatar', zone: 'Asia/Qatar' },
  { id: 'kwi', name: 'Kuwait City', country: 'Kuwait', zone: 'Asia/Kuwait' },
  { id: 'bah', name: 'Manama', country: 'Bahrain', zone: 'Asia/Bahrain' },
  { id: 'mct', name: 'Muscat', country: 'Oman', zone: 'Asia/Muscat' },
  { id: 'tlv', name: 'Tel Aviv', country: 'Israel', zone: 'Asia/Jerusalem' },
  { id: 'jrs', name: 'Jerusalem', country: 'Israel', zone: 'Asia/Jerusalem' },
  { id: 'amm', name: 'Amman', country: 'Jordan', zone: 'Asia/Amman' },
  { id: 'bey', name: 'Beirut', country: 'Lebanon', zone: 'Asia/Beirut' },
  { id: 'cai', name: 'Cairo', country: 'Egypt', zone: 'Africa/Cairo' },
  { id: 'aly', name: 'Alexandria', country: 'Egypt', zone: 'Africa/Cairo' },
  { id: 'cas', name: 'Casablanca', country: 'Morocco', zone: 'Africa/Casablanca' },
  { id: 'rak', name: 'Marrakech', country: 'Morocco', zone: 'Africa/Casablanca' },
  { id: 'tun', name: 'Tunis', country: 'Tunisia', zone: 'Africa/Tunis' },
  { id: 'alg', name: 'Algiers', country: 'Algeria', zone: 'Africa/Algiers' },
  { id: 'jnb', name: 'Johannesburg', country: 'South Africa', zone: 'Africa/Johannesburg' },
  { id: 'cpt', name: 'Cape Town', country: 'South Africa', zone: 'Africa/Johannesburg' },
  { id: 'dur', name: 'Durban', country: 'South Africa', zone: 'Africa/Johannesburg' },
  { id: 'nbo', name: 'Nairobi', country: 'Kenya', zone: 'Africa/Nairobi' },
  { id: 'los', name: 'Lagos', country: 'Nigeria', zone: 'Africa/Lagos' },
  { id: 'abj', name: 'Abuja', country: 'Nigeria', zone: 'Africa/Lagos' },
  { id: 'acc', name: 'Accra', country: 'Ghana', zone: 'Africa/Accra' },
  { id: 'add', name: 'Addis Ababa', country: 'Ethiopia', zone: 'Africa/Addis_Ababa' },

  // --- ASIA & OCEANIA ---
  { id: 'del', name: 'New Delhi', country: 'India', zone: 'Asia/Kolkata' },
  { id: 'bom', name: 'Mumbai', country: 'India', zone: 'Asia/Kolkata' },
  { id: 'blr', name: 'Bengaluru (Bangalore)', country: 'India', zone: 'Asia/Kolkata' },
  { id: 'hyd', name: 'Hyderabad', country: 'India', zone: 'Asia/Kolkata' },
  { id: 'maa', name: 'Chennai', country: 'India', zone: 'Asia/Kolkata' },
  { id: 'ccu', name: 'Kolkata', country: 'India', zone: 'Asia/Kolkata' },
  { id: 'pnq', name: 'Pune', country: 'India', zone: 'Asia/Kolkata' },
  { id: 'sin', name: 'Singapore', country: 'Singapore', zone: 'Asia/Singapore' },
  { id: 'kul', name: 'Kuala Lumpur', country: 'Malaysia', zone: 'Asia/Kuala_Lumpur' },
  { id: 'bkk', name: 'Bangkok', country: 'Thailand', zone: 'Asia/Bangkok' },
  { id: 'cnx', name: 'Chiang Mai', country: 'Thailand', zone: 'Asia/Bangkok' },
  { id: 'jkt', name: 'Jakarta', country: 'Indonesia', zone: 'Asia/Jakarta' },
  { id: 'dps', name: 'Bali (Denpasar)', country: 'Indonesia', zone: 'Asia/Makassar' },
  { id: 'mnl', name: 'Manila', country: 'Philippines', zone: 'Asia/Manila' },
  { id: 'ceb', name: 'Cebu City', country: 'Philippines', zone: 'Asia/Manila' },
  { id: 'sgn', name: 'Ho Chi Minh City', country: 'Vietnam', zone: 'Asia/Ho_Chi_Minh' },
  { id: 'han', name: 'Hanoi', country: 'Vietnam', zone: 'Asia/Bangkok' },
  { id: 'tyo', name: 'Tokyo', country: 'Japan', zone: 'Asia/Tokyo' },
  { id: 'osa', name: 'Osaka', country: 'Japan', zone: 'Asia/Tokyo' },
  { id: 'kix', name: 'Kyoto', country: 'Japan', zone: 'Asia/Tokyo' },
  { id: 'ngo', name: 'Nagoya', country: 'Japan', zone: 'Asia/Tokyo' },
  { id: 'fuk', name: 'Fukuoka', country: 'Japan', zone: 'Asia/Tokyo' },
  { id: 'sel', name: 'Seoul', country: 'South Korea', zone: 'Asia/Seoul' },
  { id: 'pus', name: 'Busan', country: 'South Korea', zone: 'Asia/Seoul' },
  { id: 'bjs', name: 'Beijing', country: 'China', zone: 'Asia/Shanghai' },
  { id: 'sha', name: 'Shanghai', country: 'China', zone: 'Asia/Shanghai' },
  { id: 'can', name: 'Guangzhou', country: 'China', zone: 'Asia/Shanghai' },
  { id: 'szx', name: 'Shenzhen', country: 'China', zone: 'Asia/Shanghai' },
  { id: 'ctu', name: 'Chengdu', country: 'China', zone: 'Asia/Shanghai' },
  { id: 'hkg', name: 'Hong Kong', country: 'Hong Kong', zone: 'Asia/Hong_Kong' },
  { id: 'tpe', name: 'Taipei', country: 'Taiwan', zone: 'Asia/Taipei' },
  { id: 'khi', name: 'Karachi', country: 'Pakistan', zone: 'Asia/Karachi' },
  { id: 'lhr_pk', name: 'Lahore', country: 'Pakistan', zone: 'Asia/Karachi' },
  { id: 'dac', name: 'Dhaka', country: 'Bangladesh', zone: 'Asia/Dhaka' },
  { id: 'cmb', name: 'Colombo', country: 'Sri Lanka', zone: 'Asia/Colombo' },
  { id: 'ktm', name: 'Kathmandu', country: 'Nepal', zone: 'Asia/Kathmandu' },
  { id: 'syd', name: 'Sydney', country: 'Australia', zone: 'Australia/Sydney' },
  { id: 'mel', name: 'Melbourne', country: 'Australia', zone: 'Australia/Melbourne' },
  { id: 'bne', name: 'Brisbane', country: 'Australia', zone: 'Australia/Brisbane' },
  { id: 'per', name: 'Perth', country: 'Australia', zone: 'Australia/Perth' },
  { id: 'adl', name: 'Adelaide', country: 'Australia', zone: 'Australia/Adelaide' },
  { id: 'ool', name: 'Gold Coast', country: 'Australia', zone: 'Australia/Brisbane' },
  { id: 'akl', name: 'Auckland', country: 'New Zealand', zone: 'Pacific/Auckland' },
  { id: 'wlg', name: 'Wellington', country: 'New Zealand', zone: 'Pacific/Auckland' },
  { id: 'chc', name: 'Christchurch', country: 'New Zealand', zone: 'Pacific/Auckland' },
  { id: 'zqn', name: 'Queenstown', country: 'New Zealand', zone: 'Pacific/Auckland' },
]

export const COMMON_TIMEZONES = [
  { label: 'Italy / Central Europe (CET/CEST)', zone: 'Europe/Rome' },
  { label: 'Cyprus / Greece / Eastern Europe (EET/EEST)', zone: 'Europe/Athens' },
  { label: 'Western Europe / UK (GMT/BST)', zone: 'Europe/London' },
  { label: 'US Eastern (New York, Miami)', zone: 'America/New_York' },
  { label: 'US Central (Chicago, Texas)', zone: 'America/Chicago' },
  { label: 'US Mountain (Denver, Utah)', zone: 'America/Denver' },
  { label: 'US Pacific (Los Angeles, Seattle)', zone: 'America/Los_Angeles' },
  { label: 'Gulf Standard Time (Dubai, Abu Dhabi)', zone: 'Asia/Dubai' },
  { label: 'India Standard Time (IST)', zone: 'Asia/Kolkata' },
  { label: 'Singapore / China (SGT/CST)', zone: 'Asia/Singapore' },
  { label: 'Japan / Korea (JST/KST)', zone: 'Asia/Tokyo' },
  { label: 'Australia Eastern (Sydney, Melbourne)', zone: 'Australia/Sydney' },
  { label: 'Coordinated Universal Time (UTC)', zone: 'UTC' },
]