export interface CityZone {
  id: string
  name: string
  country: string
  zone: string
}

export const ALL_CITIES: CityZone[] = [
  // ==========================================
  // --- 1. RUSSIA & EURASIA (All 11 Time Zones) ---
  // ==========================================
  // European Russia (UTC+3 / MSK)
  { id: 'ru_mow', name: 'Moscow', country: 'Russia', zone: 'Europe/Moscow' },
  { id: 'ru_led', name: 'Saint Petersburg', country: 'Russia', zone: 'Europe/Moscow' },
  { id: 'ru_kzn', name: 'Kazan', country: 'Russia', zone: 'Europe/Moscow' },
  { id: 'ru_goj', name: 'Nizhny Novgorod', country: 'Russia', zone: 'Europe/Moscow' },
  { id: 'ru_rov', name: 'Rostov-on-Don', country: 'Russia', zone: 'Europe/Moscow' },
  { id: 'ru_krr', name: 'Krasnodar', country: 'Russia', zone: 'Europe/Moscow' },
  { id: 'ru_voz', name: 'Voronezh', country: 'Russia', zone: 'Europe/Moscow' },
  { id: 'ru_vog', name: 'Volgograd', country: 'Russia', zone: 'Europe/Moscow' },
  { id: 'ru_aer', name: 'Sochi', country: 'Russia', zone: 'Europe/Moscow' },
  { id: 'ru_yar', name: 'Yaroslavl', country: 'Russia', zone: 'Europe/Moscow' },
  { id: 'ru_rza', name: 'Ryazan', country: 'Russia', zone: 'Europe/Moscow' },
  { id: 'ru_peh', name: 'Penza', country: 'Russia', zone: 'Europe/Moscow' },
  { id: 'ru_mcx', name: 'Makhachkala', country: 'Russia', zone: 'Europe/Moscow' },
  { id: 'ru_mmk', name: 'Murmansk', country: 'Russia', zone: 'Europe/Moscow' },
  { id: 'ru_arh', name: 'Arkhangelsk', country: 'Russia', zone: 'Europe/Moscow' },
  // Kaliningrad (UTC+2)
  { id: 'ru_kgd', name: 'Kaliningrad', country: 'Russia', zone: 'Europe/Kaliningrad' },
  // Samara Time (UTC+4)
  { id: 'ru_kuf', name: 'Samara', country: 'Russia', zone: 'Europe/Samara' },
  { id: 'ru_tlt', name: 'Tolyatti', country: 'Russia', zone: 'Europe/Samara' },
  { id: 'ru_rtw', name: 'Saratov', country: 'Russia', zone: 'Europe/Samara' },
  { id: 'ru_asf', name: 'Astrakhan', country: 'Russia', zone: 'Europe/Samara' },
  { id: 'ru_ulv', name: 'Ulyanovsk', country: 'Russia', zone: 'Europe/Samara' },
  { id: 'ru_ijx', name: 'Izhevsk', country: 'Russia', zone: 'Europe/Samara' },
  // Urals (UTC+5)
  { id: 'ru_svx', name: 'Yekaterinburg', country: 'Russia', zone: 'Asia/Yekaterinburg' },
  { id: 'ru_cek', name: 'Chelyabinsk', country: 'Russia', zone: 'Asia/Yekaterinburg' },
  { id: 'ru_ufa', name: 'Ufa', country: 'Russia', zone: 'Asia/Yekaterinburg' },
  { id: 'ru_pee', name: 'Perm', country: 'Russia', zone: 'Asia/Yekaterinburg' },
  { id: 'ru_tjm', name: 'Tyumen', country: 'Russia', zone: 'Asia/Yekaterinburg' },
  { id: 'ru_ren', name: 'Orenburg', country: 'Russia', zone: 'Asia/Yekaterinburg' },
  { id: 'ru_mgn', name: 'Magnitogorsk', country: 'Russia', zone: 'Asia/Yekaterinburg' },
  // Omsk (UTC+6)
  { id: 'ru_oms', name: 'Omsk', country: 'Russia', zone: 'Asia/Omsk' },
  // Western Siberia / Krasnoyarsk (UTC+7)
  { id: 'ru_ovb', name: 'Novosibirsk', country: 'Russia', zone: 'Asia/Novosibirsk' },
  { id: 'ru_kja', name: 'Krasnoyarsk', country: 'Russia', zone: 'Asia/Krasnoyarsk' },
  { id: 'ru_bax', name: 'Barnaul', country: 'Russia', zone: 'Asia/Barnaul' },
  { id: 'ru_tof', name: 'Tomsk', country: 'Russia', zone: 'Asia/Tomsk' },
  { id: 'ru_kej', name: 'Kemerovo', country: 'Russia', zone: 'Asia/Kemerovo' },
  { id: 'ru_noz', name: 'Novokuznetsk', country: 'Russia', zone: 'Asia/Novokuznetsk' },
  // Lake Baikal (UTC+8)
  { id: 'ru_ikt', name: 'Irkutsk', country: 'Russia', zone: 'Asia/Irkutsk' },
  { id: 'ru_uud', name: 'Ulan-Ude', country: 'Russia', zone: 'Asia/Irkutsk' },
  // Yakutsk & Transbaikalia (UTC+9)
  { id: 'ru_yks', name: 'Yakutsk', country: 'Russia', zone: 'Asia/Yakutsk' },
  { id: 'ru_hta', name: 'Chita', country: 'Russia', zone: 'Asia/Chita' },
  // Russian Far East & Vladivostok (UTC+10)
  { id: 'ru_vvo', name: 'Vladivostok', country: 'Russia', zone: 'Asia/Vladivostok' },
  { id: 'ru_khv', name: 'Khabarovsk', country: 'Russia', zone: 'Asia/Vladivostok' },
  // Magadan & Sakhalin (UTC+11)
  { id: 'ru_uus', name: 'Yuzhno-Sakhalinsk', country: 'Russia', zone: 'Asia/Sakhalin' },
  { id: 'ru_gdn', name: 'Magadan', country: 'Russia', zone: 'Asia/Magadan' },
  // Kamchatka & Chukotka (UTC+12)
  { id: 'ru_pkc', name: 'Petropavlovsk-Kamchatsky', country: 'Russia', zone: 'Asia/Kamchatka' },
  { id: 'ru_dyr', name: 'Anadyr', country: 'Russia', zone: 'Asia/Anadyr' },

  // Eurasia, Caucasus & Central Asia
  { id: 'by_msq', name: 'Minsk', country: 'Belarus', zone: 'Europe/Minsk' },
  { id: 'by_bqt', name: 'Brest', country: 'Belarus', zone: 'Europe/Minsk' },
  { id: 'by_gme', name: 'Gomel', country: 'Belarus', zone: 'Europe/Minsk' },
  { id: 'ua_kyi', name: 'Kyiv', country: 'Ukraine', zone: 'Europe/Kyiv' },
  { id: 'ua_hrk', name: 'Kharkiv', country: 'Ukraine', zone: 'Europe/Kyiv' },
  { id: 'ua_ods', name: 'Odesa', country: 'Ukraine', zone: 'Europe/Kyiv' },
  { id: 'ua_dnk', name: 'Dnipro', country: 'Ukraine', zone: 'Europe/Kyiv' },
  { id: 'ua_lwo', name: 'Lviv', country: 'Ukraine', zone: 'Europe/Kyiv' },
  { id: 'ua_ozh', name: 'Zaporizhzhia', country: 'Ukraine', zone: 'Europe/Kyiv' },
  { id: 'kz_ala', name: 'Almaty', country: 'Kazakhstan', zone: 'Asia/Almaty' },
  { id: 'kz_ast', name: 'Astana', country: 'Kazakhstan', zone: 'Asia/Almaty' },
  { id: 'kz_cit', name: 'Shymkent', country: 'Kazakhstan', zone: 'Asia/Almaty' },
  { id: 'kz_kgf', name: 'Karaganda', country: 'Kazakhstan', zone: 'Asia/Almaty' },
  { id: 'kz_akx', name: 'Aktobe', country: 'Kazakhstan', zone: 'Asia/Aqtau' },
  { id: 'uz_tas', name: 'Tashkent', country: 'Uzbekistan', zone: 'Asia/Tashkent' },
  { id: 'uz_skd', name: 'Samarkand', country: 'Uzbekistan', zone: 'Asia/Samarkand' },
  { id: 'uz_bhk', name: 'Bukhara', country: 'Uzbekistan', zone: 'Asia/Samarkand' },
  { id: 'uz_nma', name: 'Namangan', country: 'Uzbekistan', zone: 'Asia/Tashkent' },
  { id: 'kg_frn', name: 'Bishkek', country: 'Kyrgyzstan', zone: 'Asia/Bishkek' },
  { id: 'kg_oss', name: 'Osh', country: 'Kyrgyzstan', zone: 'Asia/Bishkek' },
  { id: 'tj_dyu', name: 'Dushanbe', country: 'Tajikistan', zone: 'Asia/Dushanbe' },
  { id: 'tm_asb', name: 'Ashgabat', country: 'Turkmenistan', zone: 'Asia/Ashgabat' },
  { id: 'az_gyd', name: 'Baku', country: 'Azerbaijan', zone: 'Asia/Baku' },
  { id: 'ge_tbs', name: 'Tbilisi', country: 'Georgia', zone: 'Asia/Tbilisi' },
  { id: 'ge_bus', name: 'Batumi', country: 'Georgia', zone: 'Asia/Tbilisi' },
  { id: 'am_evn', name: 'Yerevan', country: 'Armenia', zone: 'Asia/Yerevan' },
  { id: 'mn_uln', name: 'Ulaanbaatar', country: 'Mongolia', zone: 'Asia/Ulaanbaatar' },

  // ==========================================
  // --- 2. USA (All 50 States Major Hubs) ---
  // ==========================================
  // US Eastern Time
  { id: 'us_nyc', name: 'New York City', country: 'United States', zone: 'America/New_York' },
  { id: 'us_bos', name: 'Boston', country: 'United States', zone: 'America/New_York' },
  { id: 'us_mia', name: 'Miami', country: 'United States', zone: 'America/New_York' },
  { id: 'us_orl', name: 'Orlando', country: 'United States', zone: 'America/New_York' },
  { id: 'us_tpa', name: 'Tampa', country: 'United States', zone: 'America/New_York' },
  { id: 'us_fll', name: 'Fort Lauderdale', country: 'United States', zone: 'America/New_York' },
  { id: 'us_jax', name: 'Jacksonville', country: 'United States', zone: 'America/New_York' },
  { id: 'us_atl', name: 'Atlanta', country: 'United States', zone: 'America/New_York' },
  { id: 'us_was', name: 'Washington D.C.', country: 'United States', zone: 'America/New_York' },
  { id: 'us_phl', name: 'Philadelphia', country: 'United States', zone: 'America/New_York' },
  { id: 'us_pit', name: 'Pittsburgh', country: 'United States', zone: 'America/New_York' },
  { id: 'us_clt', name: 'Charlotte', country: 'United States', zone: 'America/New_York' },
  { id: 'us_rdu', name: 'Raleigh', country: 'United States', zone: 'America/New_York' },
  { id: 'us_dtw', name: 'Detroit', country: 'United States', zone: 'America/Detroit' },
  { id: 'us_ind', name: 'Indianapolis', country: 'United States', zone: 'America/Indiana/Indianapolis' },
  { id: 'us_cmh', name: 'Columbus', country: 'United States', zone: 'America/New_York' },
  { id: 'us_cle', name: 'Cleveland', country: 'United States', zone: 'America/New_York' },
  { id: 'us_cvg', name: 'Cincinnati', country: 'United States', zone: 'America/New_York' },
  { id: 'us_bal', name: 'Baltimore', country: 'United States', zone: 'America/New_York' },
  { id: 'us_ewr', name: 'Newark', country: 'United States', zone: 'America/New_York' },
  { id: 'us_jcy', name: 'Jersey City', country: 'United States', zone: 'America/New_York' },
  { id: 'us_buf', name: 'Buffalo', country: 'United States', zone: 'America/New_York' },
  { id: 'us_ric', name: 'Richmond', country: 'United States', zone: 'America/New_York' },
  { id: 'us_orf', name: 'Virginia Beach', country: 'United States', zone: 'America/New_York' },
  { id: 'us_pvd', name: 'Providence', country: 'United States', zone: 'America/New_York' },
  { id: 'us_bdr', name: 'Hartford', country: 'United States', zone: 'America/New_York' },
  { id: 'us_pwm', name: 'Portland (Maine)', country: 'United States', zone: 'America/New_York' },
  // US Central Time
  { id: 'us_chi', name: 'Chicago', country: 'United States', zone: 'America/Chicago' },
  { id: 'us_hou', name: 'Houston', country: 'United States', zone: 'America/Chicago' },
  { id: 'us_dal', name: 'Dallas - Fort Worth', country: 'United States', zone: 'America/Chicago' },
  { id: 'us_aus', name: 'Austin', country: 'United States', zone: 'America/Chicago' },
  { id: 'us_sat', name: 'San Antonio', country: 'United States', zone: 'America/Chicago' },
  { id: 'us_bna', name: 'Nashville', country: 'United States', zone: 'America/Chicago' },
  { id: 'us_mem', name: 'Memphis', country: 'United States', zone: 'America/Chicago' },
  { id: 'us_msp', name: 'Minneapolis - Saint Paul', country: 'United States', zone: 'America/Chicago' },
  { id: 'us_mke', name: 'Milwaukee', country: 'United States', zone: 'America/Chicago' },
  { id: 'us_msn', name: 'Madison', country: 'United States', zone: 'America/Chicago' },
  { id: 'us_stl', name: 'Saint Louis', country: 'United States', zone: 'America/Chicago' },
  { id: 'us_mci', name: 'Kansas City', country: 'United States', zone: 'America/Chicago' },
  { id: 'us_msy', name: 'New Orleans', country: 'United States', zone: 'America/Chicago' },
  { id: 'us_okc', name: 'Oklahoma City', country: 'United States', zone: 'America/Chicago' },
  { id: 'us_tul', name: 'Tulsa', country: 'United States', zone: 'America/Chicago' },
  { id: 'us_oma', name: 'Omaha', country: 'United States', zone: 'America/Chicago' },
  { id: 'us_dsm', name: 'Des Moines', country: 'United States', zone: 'America/Chicago' },
  { id: 'us_lit', name: 'Little Rock', country: 'United States', zone: 'America/Chicago' },
  { id: 'us_bhm', name: 'Birmingham (Alabama)', country: 'United States', zone: 'America/Chicago' },
  // US Mountain Time
  { id: 'us_den', name: 'Denver', country: 'United States', zone: 'America/Denver' },
  { id: 'us_cos', name: 'Colorado Springs', country: 'United States', zone: 'America/Denver' },
  { id: 'us_slc', name: 'Salt Lake City', country: 'United States', zone: 'America/Denver' },
  { id: 'us_abq', name: 'Albuquerque', country: 'United States', zone: 'America/Denver' },
  { id: 'us_el_paso', name: 'El Paso', country: 'United States', zone: 'America/Denver' },
  { id: 'us_boi', name: 'Boise', country: 'United States', zone: 'America/Boise' },
  // US Arizona (No Daylight Saving Time)
  { id: 'us_phx', name: 'Phoenix', country: 'United States', zone: 'America/Phoenix' },
  { id: 'us_tus', name: 'Tucson', country: 'United States', zone: 'America/Phoenix' },
  { id: 'us_msa', name: 'Mesa', country: 'United States', zone: 'America/Phoenix' },
  { id: 'us_scd', name: 'Scottsdale', country: 'United States', zone: 'America/Phoenix' },
  // US Pacific Time
  { id: 'us_lax', name: 'Los Angeles', country: 'United States', zone: 'America/Los_Angeles' },
  { id: 'us_sfo', name: 'San Francisco', country: 'United States', zone: 'America/Los_Angeles' },
  { id: 'us_sjc', name: 'San Jose (Silicon Valley)', country: 'United States', zone: 'America/Los_Angeles' },
  { id: 'us_san', name: 'San Diego', country: 'United States', zone: 'America/Los_Angeles' },
  { id: 'us_oak', name: 'Oakland', country: 'United States', zone: 'America/Los_Angeles' },
  { id: 'us_smf', name: 'Sacramento', country: 'United States', zone: 'America/Los_Angeles' },
  { id: 'us_lgb', name: 'Long Beach', country: 'United States', zone: 'America/Los_Angeles' },
  { id: 'us_ana', name: 'Anaheim', country: 'United States', zone: 'America/Los_Angeles' },
  { id: 'us_irv', name: 'Irvine', country: 'United States', zone: 'America/Los_Angeles' },
  { id: 'us_fat', name: 'Fresno', country: 'United States', zone: 'America/Los_Angeles' },
  { id: 'us_sea', name: 'Seattle', country: 'United States', zone: 'America/Los_Angeles' },
  { id: 'us_tac', name: 'Tacoma', country: 'United States', zone: 'America/Los_Angeles' },
  { id: 'us_spk', name: 'Spokane', country: 'United States', zone: 'America/Los_Angeles' },
  { id: 'us_pdx', name: 'Portland (Oregon)', country: 'United States', zone: 'America/Los_Angeles' },
  { id: 'us_las', name: 'Las Vegas', country: 'United States', zone: 'America/Los_Angeles' },
  { id: 'us_rno', name: 'Reno', country: 'United States', zone: 'America/Los_Angeles' },
  // US Alaska & Hawaii
  { id: 'us_anc', name: 'Anchorage', country: 'United States', zone: 'America/Anchorage' },
  { id: 'us_fai', name: 'Fairbanks', country: 'United States', zone: 'America/Anchorage' },
  { id: 'us_jno', name: 'Juneau', country: 'United States', zone: 'America/Juneau' },
  { id: 'us_hnl', name: 'Honolulu', country: 'United States', zone: 'Pacific/Honolulu' },
  { id: 'us_ogg', name: 'Maui (Kahului)', country: 'United States', zone: 'Pacific/Honolulu' },

  // ==========================================
  // --- 3. NORTH AMERICA (Canada, Mexico, Caribbean) ---
  // ==========================================
  // Canada
  { id: 'ca_tor', name: 'Toronto', country: 'Canada', zone: 'America/Toronto' },
  { id: 'ca_mtl', name: 'Montreal', country: 'Canada', zone: 'America/Toronto' },
  { id: 'ca_ott', name: 'Ottawa', country: 'Canada', zone: 'America/Toronto' },
  { id: 'ca_yqb', name: 'Quebec City', country: 'Canada', zone: 'America/Toronto' },
  { id: 'ca_ham', name: 'Hamilton', country: 'Canada', zone: 'America/Toronto' },
  { id: 'ca_ykw', name: 'Kitchener - Waterloo', country: 'Canada', zone: 'America/Toronto' },
  { id: 'ca_yxu', name: 'London (Ontario)', country: 'Canada', zone: 'America/Toronto' },
  { id: 'ca_yhz', name: 'Halifax', country: 'Canada', zone: 'America/Halifax' },
  { id: 'ca_yyt', name: "St. John's", country: 'Canada', zone: 'America/St_Johns' },
  { id: 'ca_ywg', name: 'Winnipeg', country: 'Canada', zone: 'America/Winnipeg' },
  { id: 'ca_yqr', name: 'Regina', country: 'Canada', zone: 'America/Regina' },
  { id: 'ca_yxe', name: 'Saskatoon', country: 'Canada', zone: 'America/Regina' },
  { id: 'ca_yyc', name: 'Calgary', country: 'Canada', zone: 'America/Edmonton' },
  { id: 'ca_yeg', name: 'Edmonton', country: 'Canada', zone: 'America/Edmonton' },
  { id: 'ca_yvr', name: 'Vancouver', country: 'Canada', zone: 'America/Vancouver' },
  { id: 'ca_yyj', name: 'Victoria', country: 'Canada', zone: 'America/Vancouver' },
  { id: 'ca_ylw', name: 'Kelowna', country: 'Canada', zone: 'America/Vancouver' },
  // Mexico
  { id: 'mx_mex', name: 'Mexico City', country: 'Mexico', zone: 'America/Mexico_City' },
  { id: 'mx_gdl', name: 'Guadalajara', country: 'Mexico', zone: 'America/Mexico_City' },
  { id: 'mx_mty', name: 'Monterrey', country: 'Mexico', zone: 'America/Monterrey' },
  { id: 'mx_pue', name: 'Puebla', country: 'Mexico', zone: 'America/Mexico_City' },
  { id: 'mx_tij', name: 'Tijuana', country: 'Mexico', zone: 'America/Tijuana' },
  { id: 'mx_cjs', name: 'Ciudad Juárez', country: 'Mexico', zone: 'America/Ciudad_Juarez' },
  { id: 'mx_bjx', name: 'León', country: 'Mexico', zone: 'America/Mexico_City' },
  { id: 'mx_mid', name: 'Mérida', country: 'Mexico', zone: 'America/Merida' },
  { id: 'mx_cun', name: 'Cancún', country: 'Mexico', zone: 'America/Cancun' },
  { id: 'mx_qro', name: 'Querétaro', country: 'Mexico', zone: 'America/Mexico_City' },
  { id: 'mx_slp', name: 'San Luis Potosí', country: 'Mexico', zone: 'America/Mexico_City' },
  { id: 'mx_hmo', name: 'Hermosillo', country: 'Mexico', zone: 'America/Hermosillo' },
  { id: 'mx_mxl', name: 'Mexicali', country: 'Mexico', zone: 'America/Tijuana' },
  { id: 'mx_cul', name: 'Culiacán', country: 'Mexico', zone: 'America/Mazatlan' },
  { id: 'mx_aca', name: 'Acapulco', country: 'Mexico', zone: 'America/Mexico_City' },
  // Caribbean & Central America
  { id: 'cu_hav', name: 'Havana', country: 'Cuba', zone: 'America/Havana' },
  { id: 'do_sdq', name: 'Santo Domingo', country: 'Dominican Republic', zone: 'America/Santo_Domingo' },
  { id: 'pr_sju', name: 'San Juan', country: 'Puerto Rico', zone: 'America/Puerto_Rico' },
  { id: 'jm_kin', name: 'Kingston', country: 'Jamaica', zone: 'America/Jamaica' },
  { id: 'bs_nas', name: 'Nassau', country: 'Bahamas', zone: 'America/Nassau' },
  { id: 'gt_gua', name: 'Guatemala City', country: 'Guatemala', zone: 'America/Guatemala' },
  { id: 'sv_sal', name: 'San Salvador', country: 'El Salvador', zone: 'America/El_Salvador' },
  { id: 'hn_tgu', name: 'Tegucigalpa', country: 'Honduras', zone: 'America/Tegucigalpa' },
  { id: 'ni_mga', name: 'Managua', country: 'Nicaragua', zone: 'America/Managua' },
  { id: 'cr_sjo', name: 'San José', country: 'Costa Rica', zone: 'America/Costa_Rica' },
  { id: 'pa_pty', name: 'Panama City', country: 'Panama', zone: 'America/Panama' },

  // ==========================================
  // --- 4. ASIA (East, Southeast, South & West Asia) ---
  // ==========================================
  // Japan
  { id: 'jp_tyo', name: 'Tokyo', country: 'Japan', zone: 'Asia/Tokyo' },
  { id: 'jp_yok', name: 'Yokohama', country: 'Japan', zone: 'Asia/Tokyo' },
  { id: 'jp_osa', name: 'Osaka', country: 'Japan', zone: 'Asia/Tokyo' },
  { id: 'jp_ngo', name: 'Nagoya', country: 'Japan', zone: 'Asia/Tokyo' },
  { id: 'jp_spk', name: 'Sapporo', country: 'Japan', zone: 'Asia/Tokyo' },
  { id: 'jp_fuk', name: 'Fukuoka', country: 'Japan', zone: 'Asia/Tokyo' },
  { id: 'jp_kbe', name: 'Kobe', country: 'Japan', zone: 'Asia/Tokyo' },
  { id: 'jp_kyo', name: 'Kyoto', country: 'Japan', zone: 'Asia/Tokyo' },
  { id: 'jp_hij', name: 'Hiroshima', country: 'Japan', zone: 'Asia/Tokyo' },
  { id: 'jp_sdj', name: 'Sendai', country: 'Japan', zone: 'Asia/Tokyo' },
  { id: 'jp_oka', name: 'Naha (Okinawa)', country: 'Japan', zone: 'Asia/Tokyo' },
  // South & North Korea
  { id: 'kr_sel', name: 'Seoul', country: 'South Korea', zone: 'Asia/Seoul' },
  { id: 'kr_pus', name: 'Busan', country: 'South Korea', zone: 'Asia/Seoul' },
  { id: 'kr_icn', name: 'Incheon', country: 'South Korea', zone: 'Asia/Seoul' },
  { id: 'kr_tae', name: 'Daegu', country: 'South Korea', zone: 'Asia/Seoul' },
  { id: 'kr_djn', name: 'Daejeon', country: 'South Korea', zone: 'Asia/Seoul' },
  { id: 'kr_gju', name: 'Gwangju', country: 'South Korea', zone: 'Asia/Seoul' },
  { id: 'kr_cju', name: 'Jeju', country: 'South Korea', zone: 'Asia/Seoul' },
  { id: 'kp_fnj', name: 'Pyongyang', country: 'North Korea', zone: 'Asia/Pyongyang' },
  // Greater China & Taiwan
  { id: 'cn_bjs', name: 'Beijing', country: 'China', zone: 'Asia/Shanghai' },
  { id: 'cn_sha', name: 'Shanghai', country: 'China', zone: 'Asia/Shanghai' },
  { id: 'cn_can', name: 'Guangzhou', country: 'China', zone: 'Asia/Shanghai' },
  { id: 'cn_szx', name: 'Shenzhen', country: 'China', zone: 'Asia/Shanghai' },
  { id: 'cn_ctu', name: 'Chengdu', country: 'China', zone: 'Asia/Shanghai' },
  { id: 'cn_ckg', name: 'Chongqing', country: 'China', zone: 'Asia/Shanghai' },
  { id: 'cn_tsn', name: 'Tianjin', country: 'China', zone: 'Asia/Shanghai' },
  { id: 'cn_wuh', name: 'Wuhan', country: 'China', zone: 'Asia/Shanghai' },
  { id: 'cn_hgh', name: 'Hangzhou', country: 'China', zone: 'Asia/Shanghai' },
  { id: 'cn_sia', name: "Xi'an", country: 'China', zone: 'Asia/Shanghai' },
  { id: 'cn_nkg', name: 'Nanjing', country: 'China', zone: 'Asia/Shanghai' },
  { id: 'cn_she', name: 'Shenyang', country: 'China', zone: 'Asia/Shanghai' },
  { id: 'cn_hrb', name: 'Harbin', country: 'China', zone: 'Asia/Shanghai' },
  { id: 'cn_tao', name: 'Qingdao', country: 'China', zone: 'Asia/Shanghai' },
  { id: 'cn_xmn', name: 'Xiamen', country: 'China', zone: 'Asia/Shanghai' },
  { id: 'cn_urc', name: 'Urumqi', country: 'China', zone: 'Asia/Urumqi' },
  { id: 'hk_hkg', name: 'Hong Kong', country: 'Hong Kong', zone: 'Asia/Hong_Kong' },
  { id: 'mo_mfm', name: 'Macau', country: 'Macau', zone: 'Asia/Macau' },
  { id: 'tw_tpe', name: 'Taipei', country: 'Taiwan', zone: 'Asia/Taipei' },
  { id: 'tw_khh', name: 'Kaohsiung', country: 'Taiwan', zone: 'Asia/Taipei' },
  { id: 'tw_txg', name: 'Taichung', country: 'Taiwan', zone: 'Asia/Taipei' },
  { id: 'tw_hsz', name: 'Hsinchu', country: 'Taiwan', zone: 'Asia/Taipei' },
  // India & South Asia
  { id: 'in_del', name: 'New Delhi', country: 'India', zone: 'Asia/Kolkata' },
  { id: 'in_bom', name: 'Mumbai', country: 'India', zone: 'Asia/Kolkata' },
  { id: 'in_blr', name: 'Bengaluru (Bangalore)', country: 'India', zone: 'Asia/Kolkata' },
  { id: 'in_hyd', name: 'Hyderabad', country: 'India', zone: 'Asia/Kolkata' },
  { id: 'in_maa', name: 'Chennai', country: 'India', zone: 'Asia/Kolkata' },
  { id: 'in_ccu', name: 'Kolkata', country: 'India', zone: 'Asia/Kolkata' },
  { id: 'in_amd', name: 'Ahmedabad', country: 'India', zone: 'Asia/Kolkata' },
  { id: 'in_pnq', name: 'Pune', country: 'India', zone: 'Asia/Kolkata' },
  { id: 'in_stv', name: 'Surat', country: 'India', zone: 'Asia/Kolkata' },
  { id: 'in_jai', name: 'Jaipur', country: 'India', zone: 'Asia/Kolkata' },
  { id: 'in_lko', name: 'Lucknow', country: 'India', zone: 'Asia/Kolkata' },
  { id: 'in_cok', name: 'Kochi (Cochin)', country: 'India', zone: 'Asia/Kolkata' },
  { id: 'in_trv', name: 'Thiruvananthapuram', country: 'India', zone: 'Asia/Kolkata' },
  { id: 'in_ixc', name: 'Chandigarh', country: 'India', zone: 'Asia/Kolkata' },
  { id: 'in_atq', name: 'Amritsar', country: 'India', zone: 'Asia/Kolkata' },
  { id: 'in_gau', name: 'Guwahati', country: 'India', zone: 'Asia/Kolkata' },
  { id: 'pk_khi', name: 'Karachi', country: 'Pakistan', zone: 'Asia/Karachi' },
  { id: 'pk_lhe', name: 'Lahore', country: 'Pakistan', zone: 'Asia/Karachi' },
  { id: 'pk_isb', name: 'Islamabad - Rawalpindi', country: 'Pakistan', zone: 'Asia/Karachi' },
  { id: 'pk_pew', name: 'Peshawar', country: 'Pakistan', zone: 'Asia/Karachi' },
  { id: 'bd_dac', name: 'Dhaka', country: 'Bangladesh', zone: 'Asia/Dhaka' },
  { id: 'bd_cgp', name: 'Chittagong', country: 'Bangladesh', zone: 'Asia/Dhaka' },
  { id: 'lk_cmb', name: 'Colombo', country: 'Sri Lanka', zone: 'Asia/Colombo' },
  { id: 'np_ktm', name: 'Kathmandu', country: 'Nepal', zone: 'Asia/Kathmandu' },
  // Southeast Asia
  { id: 'sg_sin', name: 'Singapore', country: 'Singapore', zone: 'Asia/Singapore' },
  { id: 'my_kul', name: 'Kuala Lumpur', country: 'Malaysia', zone: 'Asia/Kuala_Lumpur' },
  { id: 'my_pen', name: 'Penang (George Town)', country: 'Malaysia', zone: 'Asia/Kuala_Lumpur' },
  { id: 'my_jhb', name: 'Johor Bahru', country: 'Malaysia', zone: 'Asia/Kuala_Lumpur' },
  { id: 'my_bki', name: 'Kota Kinabalu', country: 'Malaysia', zone: 'Asia/Kuching' },
  { id: 'th_bkk', name: 'Bangkok', country: 'Thailand', zone: 'Asia/Bangkok' },
  { id: 'th_cnx', name: 'Chiang Mai', country: 'Thailand', zone: 'Asia/Bangkok' },
  { id: 'th_hkt', name: 'Phuket', country: 'Thailand', zone: 'Asia/Bangkok' },
  { id: 'th_pty', name: 'Pattaya', country: 'Thailand', zone: 'Asia/Bangkok' },
  { id: 'id_jkt', name: 'Jakarta', country: 'Indonesia', zone: 'Asia/Jakarta' },
  { id: 'id_sub', name: 'Surabaya', country: 'Indonesia', zone: 'Asia/Jakarta' },
  { id: 'id_bdo', name: 'Bandung', country: 'Indonesia', zone: 'Asia/Jakarta' },
  { id: 'id_mes', name: 'Medan', country: 'Indonesia', zone: 'Asia/Jakarta' },
  { id: 'id_dps', name: 'Bali (Denpasar)', country: 'Indonesia', zone: 'Asia/Makassar' },
  { id: 'id_upg', name: 'Makassar', country: 'Indonesia', zone: 'Asia/Makassar' },
  { id: 'ph_mnl', name: 'Manila', country: 'Philippines', zone: 'Asia/Manila' },
  { id: 'ph_ceb', name: 'Cebu City', country: 'Philippines', zone: 'Asia/Manila' },
  { id: 'ph_dvo', name: 'Davao City', country: 'Philippines', zone: 'Asia/Manila' },
  { id: 'vn_sgn', name: 'Ho Chi Minh City', country: 'Vietnam', zone: 'Asia/Ho_Chi_Minh' },
  { id: 'vn_han', name: 'Hanoi', country: 'Vietnam', zone: 'Asia/Bangkok' },
  { id: 'vn_dad', name: 'Da Nang', country: 'Vietnam', zone: 'Asia/Bangkok' },
  { id: 'mm_rgn', name: 'Yangon', country: 'Myanmar', zone: 'Asia/Yangon' },
  { id: 'kh_pnh', name: 'Phnom Penh', country: 'Cambodia', zone: 'Asia/Phnom_Penh' },
  { id: 'la_vte', name: 'Vientiane', country: 'Laos', zone: 'Asia/Vientiane' },
  { id: 'bn_bwn', name: 'Bandar Seri Begawan', country: 'Brunei', zone: 'Asia/Brunei' },

  // ==========================================
  // --- 5. OCEANIA (Australia, NZ & Pacific) ---
  // ==========================================
  // Australia
  { id: 'au_syd', name: 'Sydney', country: 'Australia', zone: 'Australia/Sydney' },
  { id: 'au_mel', name: 'Melbourne', country: 'Australia', zone: 'Australia/Melbourne' },
  { id: 'au_bne', name: 'Brisbane', country: 'Australia', zone: 'Australia/Brisbane' },
  { id: 'au_per', name: 'Perth', country: 'Australia', zone: 'Australia/Perth' },
  { id: 'au_adl', name: 'Adelaide', country: 'Australia', zone: 'Australia/Adelaide' },
  { id: 'au_ool', name: 'Gold Coast', country: 'Australia', zone: 'Australia/Brisbane' },
  { id: 'au_cbr', name: 'Canberra', country: 'Australia', zone: 'Australia/Sydney' },
  { id: 'au_ntl', name: 'Newcastle', country: 'Australia', zone: 'Australia/Sydney' },
  { id: 'au_wlg_au', name: 'Wollongong', country: 'Australia', zone: 'Australia/Sydney' },
  { id: 'au_mcq', name: 'Sunshine Coast', country: 'Australia', zone: 'Australia/Brisbane' },
  { id: 'au_gex', name: 'Geelong', country: 'Australia', zone: 'Australia/Melbourne' },
  { id: 'au_hba', name: 'Hobart', country: 'Australia', zone: 'Australia/Hobart' },
  { id: 'au_lcu', name: 'Launceston', country: 'Australia', zone: 'Australia/Hobart' },
  { id: 'au_tsr', name: 'Townsville', country: 'Australia', zone: 'Australia/Brisbane' },
  { id: 'au_cns', name: 'Cairns', country: 'Australia', zone: 'Australia/Brisbane' },
  { id: 'au_drw', name: 'Darwin', country: 'Australia', zone: 'Australia/Darwin' },
  { id: 'au_asp', name: 'Alice Springs', country: 'Australia', zone: 'Australia/Darwin' },
  // New Zealand
  { id: 'nz_akl', name: 'Auckland', country: 'New Zealand', zone: 'Pacific/Auckland' },
  { id: 'nz_wlg', name: 'Wellington', country: 'New Zealand', zone: 'Pacific/Auckland' },
  { id: 'nz_chc', name: 'Christchurch', country: 'New Zealand', zone: 'Pacific/Auckland' },
  { id: 'nz_hlz', name: 'Hamilton', country: 'New Zealand', zone: 'Pacific/Auckland' },
  { id: 'nz_trg', name: 'Tauranga', country: 'New Zealand', zone: 'Pacific/Auckland' },
  { id: 'nz_dud', name: 'Dunedin', country: 'New Zealand', zone: 'Pacific/Auckland' },
  { id: 'nz_zqn', name: 'Queenstown', country: 'New Zealand', zone: 'Pacific/Auckland' },
  // Pacific Island Nations & Territories
  { id: 'pg_pom', name: 'Port Moresby', country: 'Papua New Guinea', zone: 'Pacific/Port_Moresby' },
  { id: 'fj_nan', name: 'Suva / Nadi', country: 'Fiji', zone: 'Pacific/Fiji' },
  { id: 'nc_nou', name: 'Nouméa', country: 'New Caledonia', zone: 'Pacific/Noumea' },
  { id: 'pf_ppt', name: 'Papeete (Tahiti)', country: 'French Polynesia', zone: 'Pacific/Tahiti' },
  { id: 'ws_apw', name: 'Apia', country: 'Samoa', zone: 'Pacific/Apia' },
  { id: 'as_ppg', name: 'Pago Pago', country: 'American Samoa', zone: 'Pacific/Pago_Pago' },
  { id: 'to_tbu', name: "Nuku'alofa", country: 'Tonga', zone: 'Pacific/Tongatapu' },
  { id: 'vu_vli', name: 'Port Vila', country: 'Vanuatu', zone: 'Pacific/Efate' },
  { id: 'gu_gum', name: 'Guam', country: 'Guam (USA)', zone: 'Pacific/Guam' },
  { id: 'mp_spn', name: 'Saipan', country: 'Northern Mariana Islands', zone: 'Pacific/Saipan' },

  // ==========================================
  // --- 6. EUROPE (Complete Western, Central & Mediterranean) ---
  // ==========================================
  // Italy Regional
  { id: 'it_rom', name: 'Rome', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'it_mil', name: 'Milan', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'it_nap', name: 'Naples', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'it_trn', name: 'Turin (Torino)', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'it_pmo', name: 'Palermo', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'it_goa', name: 'Genoa (Genova)', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'it_blq', name: 'Bologna', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'it_flr', name: 'Florence (Firenze)', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'it_cta', name: 'Catania', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'it_bri', name: 'Bari', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'it_vce', name: 'Venice (Venezia)', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'it_vrn', name: 'Verona', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'it_pad', name: 'Padua (Padova)', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'it_trs', name: 'Trieste', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'it_bgy', name: 'Bergamo', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'it_psa', name: 'Pisa', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'it_sie', name: 'Siena', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'it_cag', name: 'Cagliari', country: 'Italy', zone: 'Europe/Rome' },
  { id: 'it_rni', name: 'Rimini', country: 'Italy', zone: 'Europe/Rome' },
  // Cyprus & Greece
  { id: 'cy_nic', name: 'Nicosia', country: 'Cyprus', zone: 'Asia/Nicosia' },
  { id: 'cy_lim', name: 'Limassol', country: 'Cyprus', zone: 'Asia/Nicosia' },
  { id: 'cy_lca', name: 'Larnaca', country: 'Cyprus', zone: 'Asia/Nicosia' },
  { id: 'cy_pfo', name: 'Paphos', country: 'Cyprus', zone: 'Asia/Nicosia' },
  { id: 'gr_ath', name: 'Athens', country: 'Greece', zone: 'Europe/Athens' },
  { id: 'gr_skg', name: 'Thessaloniki', country: 'Greece', zone: 'Europe/Athens' },
  { id: 'gr_her', name: 'Heraklion (Crete)', country: 'Greece', zone: 'Europe/Athens' },
  { id: 'gr_rho', name: 'Rhodes', country: 'Greece', zone: 'Europe/Athens' },
  { id: 'gr_cfu', name: 'Corfu (Kerkyra)', country: 'Greece', zone: 'Europe/Athens' },
  // UK, Ireland, France, Germany, Spain, etc.
  { id: 'gb_lon', name: 'London', country: 'United Kingdom', zone: 'Europe/London' },
  { id: 'gb_man', name: 'Manchester', country: 'United Kingdom', zone: 'Europe/London' },
  { id: 'gb_bhx', name: 'Birmingham', country: 'United Kingdom', zone: 'Europe/London' },
  { id: 'gb_edi', name: 'Edinburgh', country: 'United Kingdom', zone: 'Europe/London' },
  { id: 'ie_dub', name: 'Dublin', country: 'Ireland', zone: 'Europe/Dublin' },
  { id: 'fr_par', name: 'Paris', country: 'France', zone: 'Europe/Paris' },
  { id: 'fr_lyo', name: 'Lyon', country: 'France', zone: 'Europe/Paris' },
  { id: 'fr_mrs', name: 'Marseille', country: 'France', zone: 'Europe/Paris' },
  { id: 'fr_nce', name: 'Nice', country: 'France', zone: 'Europe/Paris' },
  { id: 'de_ber', name: 'Berlin', country: 'Germany', zone: 'Europe/Berlin' },
  { id: 'de_mun', name: 'Munich', country: 'Germany', zone: 'Europe/Berlin' },
  { id: 'de_fra', name: 'Frankfurt', country: 'Germany', zone: 'Europe/Berlin' },
  { id: 'de_ham', name: 'Hamburg', country: 'Germany', zone: 'Europe/Berlin' },
  { id: 'de_cgn', name: 'Cologne', country: 'Germany', zone: 'Europe/Berlin' },
  { id: 'es_mad', name: 'Madrid', country: 'Spain', zone: 'Europe/Madrid' },
  { id: 'es_bcn', name: 'Barcelona', country: 'Spain', zone: 'Europe/Madrid' },
  { id: 'es_vlc', name: 'Valencia', country: 'Spain', zone: 'Europe/Madrid' },
  { id: 'es_svq', name: 'Seville', country: 'Spain', zone: 'Europe/Madrid' },
  { id: 'es_agp', name: 'Málaga', country: 'Spain', zone: 'Europe/Madrid' },
  { id: 'es_ibz', name: 'Ibiza', country: 'Spain', zone: 'Europe/Madrid' },
  { id: 'nl_ams', name: 'Amsterdam', country: 'Netherlands', zone: 'Europe/Amsterdam' },
  { id: 'nl_rtm', name: 'Rotterdam', country: 'Netherlands', zone: 'Europe/Amsterdam' },
  { id: 'be_bru', name: 'Brussels', country: 'Belgium', zone: 'Europe/Brussels' },
  { id: 'be_anr', name: 'Antwerp', country: 'Belgium', zone: 'Europe/Brussels' },
  { id: 'pt_lis', name: 'Lisbon', country: 'Portugal', zone: 'Europe/Lisbon' },
  { id: 'pt_opo', name: 'Porto', country: 'Portugal', zone: 'Europe/Lisbon' },
  { id: 'at_vie', name: 'Vienna', country: 'Austria', zone: 'Europe/Vienna' },
  { id: 'ch_zur', name: 'Zurich', country: 'Switzerland', zone: 'Europe/Zurich' },
  { id: 'ch_gva', name: 'Geneva', country: 'Switzerland', zone: 'Europe/Zurich' },
  { id: 'se_sto', name: 'Stockholm', country: 'Sweden', zone: 'Europe/Stockholm' },
  { id: 'no_osl', name: 'Oslo', country: 'Norway', zone: 'Europe/Oslo' },
  { id: 'dk_cph', name: 'Copenhagen', country: 'Denmark', zone: 'Europe/Copenhagen' },
  { id: 'fi_hel', name: 'Helsinki', country: 'Finland', zone: 'Europe/Helsinki' },
  { id: 'pl_war', name: 'Warsaw', country: 'Poland', zone: 'Europe/Warsaw' },
  { id: 'pl_krk', name: 'Kraków', country: 'Poland', zone: 'Europe/Warsaw' },
  { id: 'cz_prg', name: 'Prague', country: 'Czech Republic', zone: 'Europe/Prague' },
  { id: 'hu_bud', name: 'Budapest', country: 'Hungary', zone: 'Europe/Budapest' },
  { id: 'ro_buc', name: 'Bucharest', country: 'Romania', zone: 'Europe/Bucharest' },
  { id: 'bg_sof', name: 'Sofia', country: 'Bulgaria', zone: 'Europe/Sofia' },
  { id: 'hr_zag', name: 'Zagreb', country: 'Croatia', zone: 'Europe/Zagreb' },
  { id: 'rs_bel', name: 'Belgrade', country: 'Serbia', zone: 'Europe/Belgrade' },
  { id: 'tr_ist', name: 'Istanbul', country: 'Turkey', zone: 'Europe/Istanbul' },
  { id: 'tr_ank', name: 'Ankara', country: 'Turkey', zone: 'Europe/Istanbul' },

  // ==========================================
  // --- 7. LATIN AMERICA, MIDDLE EAST & AFRICA ---
  // ==========================================
  { id: 'br_sao', name: 'São Paulo', country: 'Brazil', zone: 'America/Sao_Paulo' },
  { id: 'br_rio', name: 'Rio de Janeiro', country: 'Brazil', zone: 'America/Sao_Paulo' },
  { id: 'ar_bue', name: 'Buenos Aires', country: 'Argentina', zone: 'America/Argentina/Buenos_Aires' },
  { id: 'co_bog', name: 'Bogotá', country: 'Colombia', zone: 'America/Bogota' },
  { id: 'pe_lim', name: 'Lima', country: 'Peru', zone: 'America/Lima' },
  { id: 'cl_scl', name: 'Santiago', country: 'Chile', zone: 'America/Santiago' },
  { id: 'ae_dxb', name: 'Dubai', country: 'United Arab Emirates', zone: 'Asia/Dubai' },
  { id: 'ae_auh', name: 'Abu Dhabi', country: 'United Arab Emirates', zone: 'Asia/Dubai' },
  { id: 'sa_ruh', name: 'Riyadh', country: 'Saudi Arabia', zone: 'Asia/Riyadh' },
  { id: 'qa_doh', name: 'Doha', country: 'Qatar', zone: 'Asia/Qatar' },
  { id: 'kw_kwi', name: 'Kuwait City', country: 'Kuwait', zone: 'Asia/Kuwait' },
  { id: 'il_tlv', name: 'Tel Aviv', country: 'Israel', zone: 'Asia/Jerusalem' },
  { id: 'eg_cai', name: 'Cairo', country: 'Egypt', zone: 'Africa/Cairo' },
  { id: 'za_jnb', name: 'Johannesburg', country: 'South Africa', zone: 'Africa/Johannesburg' },
  { id: 'za_cpt', name: 'Cape Town', country: 'South Africa', zone: 'Africa/Johannesburg' },
  { id: 'ke_nbo', name: 'Nairobi', country: 'Kenya', zone: 'Africa/Nairobi' },
  { id: 'ng_los', name: 'Lagos', country: 'Nigeria', zone: 'Africa/Lagos' },
]

export const COMMON_TIMEZONES = [
  { label: 'Moscow Standard Time (MSK, UTC+3)', zone: 'Europe/Moscow' },
  { label: 'Yekaterinburg Time (YEKT, UTC+5)', zone: 'Asia/Yekaterinburg' },
  { label: 'Novosibirsk / Krasnoyarsk (UTC+7)', zone: 'Asia/Novosibirsk' },
  { label: 'Vladivostok Time (VLAT, UTC+10)', zone: 'Asia/Vladivostok' },
  { label: 'US Eastern (New York, Miami, Atlanta)', zone: 'America/New_York' },
  { label: 'US Central (Chicago, Houston, Dallas)', zone: 'America/Chicago' },
  { label: 'US Mountain (Denver, Salt Lake City)', zone: 'America/Denver' },
  { label: 'US Arizona (Phoenix, Mesa)', zone: 'America/Phoenix' },
  { label: 'US Pacific (Los Angeles, San Francisco, Seattle)', zone: 'America/Los_Angeles' },
  { label: 'US Alaska (Anchorage, Fairbanks)', zone: 'America/Anchorage' },
  { label: 'US Hawaii (Honolulu)', zone: 'Pacific/Honolulu' },
  { label: 'Canada Pacific (Vancouver, Victoria)', zone: 'America/Vancouver' },
  { label: 'Canada Eastern (Toronto, Montreal, Ottawa)', zone: 'America/Toronto' },
  { label: 'Mexico Central (Mexico City, Guadalajara, Monterrey)', zone: 'America/Mexico_City' },
  { label: 'Japan / Korea Standard (JST/KST, UTC+9)', zone: 'Asia/Tokyo' },
  { label: 'China / Singapore / Taiwan / Hong Kong (CST/SGT, UTC+8)', zone: 'Asia/Shanghai' },
  { label: 'India Standard Time (IST, UTC+5:30)', zone: 'Asia/Kolkata' },
  { label: 'Pakistan Standard Time (PKT, UTC+5)', zone: 'Asia/Karachi' },
  { label: 'Indochina / Thailand / Vietnam (ICT, UTC+7)', zone: 'Asia/Bangkok' },
  { label: 'Australia Eastern (Sydney, Melbourne, Canberra)', zone: 'Australia/Sydney' },
  { label: 'Australia Brisbane / Queensland (AEST, UTC+10)', zone: 'Australia/Brisbane' },
  { label: 'Australia Western / Perth (AWST, UTC+8)', zone: 'Australia/Perth' },
  { label: 'New Zealand (Auckland, Wellington, Christchurch)', zone: 'Pacific/Auckland' },
  { label: 'Italy / Central Europe (CET/CEST)', zone: 'Europe/Rome' },
  { label: 'Cyprus / Greece / Eastern Europe (EET/EEST)', zone: 'Europe/Athens' },
  { label: 'Western Europe / UK (GMT/BST)', zone: 'Europe/London' },
  { label: 'Gulf Standard Time (Dubai, Abu Dhabi, Doha)', zone: 'Asia/Dubai' },
  { label: 'Coordinated Universal Time (UTC)', zone: 'UTC' },
]